image: google/cloud-sdk:alpine

before_script:
  - apk add --update make docker

services:
  - docker:dind

build:
  script:
    - make build
    - make release

push_docker_image:
  script:
    - make push


