FROM haskell:8.4

RUN apt-get update && apt-get install -y curl lsb-release
RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

RUN stack install hpack --install-ghc
RUN apt-get update && apt-get install -y libpq-dev docker google-cloud-sdk

COPY stack.yaml .
COPY package.yaml .

RUN stack build --only-dependencies 
