FROM alpine:latest

RUN apk upgrade --update-cache --available
RUN apk add postgresql-client ca-certificates

COPY application /application

COPY migrations /application/migrations

COPY entrypoint.sh /application/entrypoint.sh

WORKDIR /application

ENTRYPOINT ["./entrypoint.sh"]
