FROM debian:stretch

RUN apt-get update && \
    apt-get install -y postgresql-client

COPY application /application

COPY migrations /application/migrations

COPY entrypoint.sh /application/entrypoint.sh

WORKDIR /application

ENTRYPOINT ["./entrypoint.sh"]
