name:                api
version:             0.1.0.0

dependencies:
- aeson
- base >= 4.7 && < 5
- base58-bytestring
- connection
- email-validate
- http-client
- http-client-tls
- http-types
- postgresql-simple
- postgresql-simple-migration
- pwstore-fast
- random
- resource-pool
- rio
- safe-exceptions
- time
- uuid
- yaml

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app/Api
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
    - megaparsec
    - scotty
    - wai
    - wai-cors

  deployment-runner:
    main:                Main.hs
    source-dirs:         app/DeploymentRunner
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api

  job-status-checker:
    main:                Main.hs
    source-dirs:         app/JobStatusChecker
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
