name:                api
version:             0.1.0.0

dependencies:
- aeson
- base >= 4.7 && < 5
- base58-bytestring
- bytestring
- connection
- data-default-class
- email-validate
- esqueleto
- graphql-api >= 0.3 && < 0.4
- hashable
- haxl
- http-client
- http-client-tls
- http-types
- persistent
- persistent-postgresql
- persistent-template
- postgresql-simple
- postgresql-simple-migration
- pwstore-fast >= 2.4 && < 3
- megaparsec
- monad-logger
- mtl
- random
- resource-pool
- rio
- safe-exceptions
- SHA
- time
- uuid
- yaml
- yesod
- yesod-core
- wai
- wai-cors
- wai-extra
- warp

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src

executables:
  api-exe:
    main:                Api.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Api
    dependencies:
    - api

  background-job-runner:
    main:                BackgroundJobRunner.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is BackgroundJobRunner
    dependencies:
    - api

  deployment-runner:
    main:                DeploymentRunner.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is DeploymentRunner
    dependencies:
    - api

  job-status-checker:
    main:                JobStatusChecker.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is JobStatusChecker
    dependencies:
    - api

  print-migrations:
    main:                PrintMigrations.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is PrintMigrations
    dependencies:
    - api

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
    - hspec
