name:                coolops-api
version:             0.1.0.0

dependencies:
- aeson
- base >= 4.7 && < 5
- base58-bytestring
- bytestring
- connection
- data-default-class
- email-validate
- esqueleto
- graphql-api >= 0.3 && < 0.4
- hashable
- haxl
- http-client
- http-client-tls
- http-types
- persistent
- persistent-postgresql
- persistent-template
- postgresql-simple
- postgresql-simple-migration
- pwstore-fast >= 2.4 && < 3
- megaparsec
- monad-logger
- mtl
- random
- resource-pool
- rio
- safe-exceptions
- SHA
- time
- uuid
- yaml
- yesod
- yesod-core
- wai
- wai-cors
- wai-extra
- warp

default-extensions:
- NoImplicitPrelude

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  api-exe:
    main:                Api.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Api
    ld-options:
    - -static
    - -I/usr/include/postgresql
    - -lpq
    dependencies:
    - coolops-api

  background-job-runner:
    main:                BackgroundJobRunner.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is BackgroundJobRunner
    ld-options:
    - -static
    dependencies:
    - coolops-api

  deployment-runner:
    main:                DeploymentRunner.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is DeploymentRunner
    ld-options:
    - -static
    - -I/usr/include/postgresql
    - -lpq
    dependencies:
    - coolops-api

  job-status-checker:
    main:                JobStatusChecker.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is JobStatusChecker
    ld-options:
    - -static
    - -I/usr/include/postgresql
    - -lpq
    dependencies:
    - coolops-api

  print-migrations:
    main:                PrintMigrations.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is PrintMigrations
    ld-options:
    - -static
    - -I/usr/include/postgresql
    - -lpq
    dependencies:
    - coolops-api

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coolops-api
    - hspec
