ALTER TABLE "background_jobs" ALTER COLUMN "params" SET DEFAULT '{}'::jsonb;
UPDATE "background_jobs" SET "params"='{}'::jsonb WHERE "params" IS NULL;
ALTER TABLE "background_jobs" ALTER COLUMN "params" SET NOT NULL;
ALTER TABLE "background_jobs" ALTER COLUMN "next_retry" TYPE TIMESTAMP WITH TIME ZONE USING "next_retry" AT TIME ZONE 'UTC';
ALTER TABLE "background_jobs" ALTER COLUMN "finished_at" TYPE TIMESTAMP WITH TIME ZONE USING "finished_at" AT TIME ZONE 'UTC';
ALTER TABLE "background_jobs" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "background_jobs" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "builds" ALTER COLUMN "params" SET DEFAULT '{}'::jsonb;
UPDATE "builds" SET "params"='{}'::jsonb WHERE "params" IS NULL;
ALTER TABLE "builds" ALTER COLUMN "params" SET NOT NULL;
ALTER TABLE "builds" ADD CONSTRAINT "builds_project_id_fkey" FOREIGN KEY("project_id") REFERENCES "projects"("id") ON DELETE CASCADE;
ALTER TABLE "builds" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "builds" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "companies" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "companies" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "companies" DROP COLUMN "onboarding_completed";
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_build_id_fkey" FOREIGN KEY("build_id") REFERENCES "builds"("id") ON DELETE RESTRICT;
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_environment_id_fkey" FOREIGN KEY("environment_id") REFERENCES "environments"("id") ON DELETE CASCADE;
ALTER TABLE "deployments" ALTER COLUMN "deployment_started_at" TYPE TIMESTAMP WITH TIME ZONE USING "deployment_started_at" AT TIME ZONE 'UTC';
ALTER TABLE "deployments" ALTER COLUMN "deployment_finished_at" TYPE TIMESTAMP WITH TIME ZONE USING "deployment_finished_at" AT TIME ZONE 'UTC';
ALTER TABLE "deployments" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "deployments" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "environments" ALTER COLUMN "env_vars" SET DEFAULT '{}'::jsonb;
UPDATE "environments" SET "env_vars"='{}'::jsonb WHERE "env_vars" IS NULL;
ALTER TABLE "environments" ALTER COLUMN "env_vars" SET NOT NULL;
ALTER TABLE "environments" ADD CONSTRAINT "environments_project_id_fkey" FOREIGN KEY("project_id") REFERENCES "projects"("id") ON DELETE CASCADE;
ALTER TABLE "environments" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "environments" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "environments" ALTER COLUMN "slug" SET NOT NULL;
ALTER TABLE "projects" ADD CONSTRAINT "projects_company_id_fkey" FOREIGN KEY("company_id") REFERENCES "companies"("id") ON DELETE CASCADE;
ALTER TABLE "projects" ALTER COLUMN "slug" SET NOT NULL;
ALTER TABLE "projects" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "projects" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_access_tokens" ADD CONSTRAINT "slack_access_tokens_company_id_fkey" FOREIGN KEY("company_id") REFERENCES "companies"("id") ON DELETE CASCADE;
ALTER TABLE "slack_access_tokens" ALTER COLUMN "scopes" TYPE text;
ALTER TABLE "slack_access_tokens" ALTER COLUMN "user_access_token" TYPE text;
ALTER TABLE "slack_access_tokens" ALTER COLUMN "bot_access_token" TYPE text;
ALTER TABLE "slack_access_tokens" ALTER COLUMN "created_at" DROP DEFAULT;
ALTER TABLE "slack_access_tokens" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_access_tokens" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "slack_access_tokens" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_build_messages" ADD CONSTRAINT "slack_build_messages_build_id_fkey" FOREIGN KEY("build_id") REFERENCES "builds"("id") ON DELETE CASCADE;
ALTER TABLE "slack_build_messages" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_build_messages" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_deployments" ADD CONSTRAINT "slack_deployments_build_message_id_fkey" FOREIGN KEY("build_message_id") REFERENCES "slack_build_messages"("id") ON DELETE CASCADE;
ALTER TABLE "slack_deployments" ADD CONSTRAINT "slack_deployments_deployment_id_fkey" FOREIGN KEY("deployment_id") REFERENCES "deployments"("id") ON DELETE CASCADE;
ALTER TABLE "slack_deployments" ALTER COLUMN "slack_user_name" TYPE text;
ALTER TABLE "slack_deployments" ALTER COLUMN "deployed_at" TYPE TIMESTAMP WITH TIME ZONE USING "deployed_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_deployments" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_deployments" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_project_integrations" ADD CONSTRAINT "slack_project_integrations_project_id_fkey" FOREIGN KEY("project_id") REFERENCES "projects"("id") ON DELETE CASCADE;
ALTER TABLE "slack_project_integrations" ALTER COLUMN "created_at" DROP DEFAULT;
ALTER TABLE "slack_project_integrations" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "slack_project_integrations" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "slack_project_integrations" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';
ALTER TABLE "users" ADD CONSTRAINT "users_company_id_fkey" FOREIGN KEY("company_id") REFERENCES "companies"("id") ON DELETE CASCADE;
ALTER TABLE "users" ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE "users" ALTER COLUMN "updated_at" TYPE TIMESTAMP WITH TIME ZONE USING "updated_at" AT TIME ZONE 'UTC';


ALTER TABLE "builds" DROP CONSTRAINT "builds_project_id_fk";
ALTER TABLE "deployments" DROP CONSTRAINT "deployments_build_id_fk";
ALTER TABLE "deployments" DROP CONSTRAINT "deployments_environment_id_fk";
ALTER TABLE "environments" DROP CONSTRAINT "environments_project_id_fk";
ALTER TABLE "projects" DROP CONSTRAINT "projects_company_id_fk";
ALTER TABLE "slack_access_tokens" DROP CONSTRAINT "slack_access_tokens_company_id_fk";
ALTER TABLE "slack_build_messages" DROP CONSTRAINT "slack_build_messages_build_id_fk";
ALTER TABLE "slack_deployments" DROP CONSTRAINT "slack_deployments_build_message_id_fk";
ALTER TABLE "slack_deployments" DROP CONSTRAINT "slack_deployments_deployment_id_fk";
ALTER TABLE "slack_project_integrations" DROP CONSTRAINT "slack_project_integrations_project_id_fk";
ALTER TABLE "users" DROP CONSTRAINT "users_company_id_fk";
