version: 2

jobs:
  build:
    docker:
      - image: coolopsio/api-buildbase:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: hlint .
      - run: VERSION=$(echo $CIRCLE_BRANCH | tr "/" "-")-${CIRCLE_SHA1} make build
      - run: VERSION=$(echo $CIRCLE_BRANCH | tr "/" "-")-${CIRCLE_SHA1} make push
  deploy:
    docker:
      - image: coolopsio/api-buildbase:latest
    steps:
      - run: VERSION=$(echo $CIRCLE_BRANCH | tr "/" "-")-${CIRCLE_SHA1} make notify_coolops

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
            - lint

